stages:
  - lint
  - test
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y python3 python3-pip python3-venv docker.io

lint:
  stage: lint
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install flake8
    - flake8 . --exclude=venv

test:
  stage: test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pytest

build:
  stage: build
  script:
    - docker build -t my-flask-app .

deploy:
  stage: deploy
  script:
    - docker run -d -p 5000:5000 my-flask-app
