image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - lint
  - test
  - build
  - deploy

before_script:
  - apk update
  - apk add --no-cache python3 py3-pip
  - python3 -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

lint:
  stage: lint
  script:
    - pip install flake8
    - flake8 . --exclude=venv

test:
  stage: test
  script:
    - pytest

build:
  stage: build
  script:
    - echo "Building Docker image"
    - docker version
    - docker info
    - docker build -t my-flask-app:latest .
    - docker images  # Verify image is built
    - docker image inspect my-flask-app:latest  # Inspect the image

deploy:
  stage: deploy
  script:
    - echo "Running Docker container"
    - docker images  # Verify image is present before running
    - docker run -d -p 5000:5000 my-flask-app:latest
