# .gitlab-ci.yml
stages:
  - test
  - deploy

before_script:
  - apt-get update
  - apt-get install -y python3 python3-pip python3-venv

test:
  stage: test
  script:
    - python3 -m venv venv
    - source venv/bin/activate
    - python --version
    - pip install -r requirements.txt
    - python hello.py

deploy:
  stage: deploy
  script:
    - echo "Deploying the application..."
    # Add your deployment scripts here
